### ISSUE TITLE
TogetherCrew Bot Application Configuration and Redirects Update Request 

### ISSUE THREAD

**Issue by Behzad-rabiei** [RnDAO/tc-discordBot#45]
### Description:
we need some essential updates to the configuration of our Discord Developer Application.
This would involve modifications in two areas - Bot Settings and OAuth2 Redirects.

**1. Bot Settings:**
We need to enable the following options:
    - PRESENCE INTENT
    - SERVER MEMBERS INTENT
    - MESSAGE CONTENT INTENT

Please follow the below steps to accomplish this:
    - Navigate to the [Discord Developer Applications](https://discord.com/developers/applications)
    - Select the 'TogetherCrew Bot' application
    - Access the 'Bot' section and turn on the specified settings

**2. OAuth2 Redirects:**
We must ensure our OAuth2 section includes the following Redirect URIs:
    - https://api.togethercrew.com/api/v1/auth/try-now/callback
    - https://api.togethercrew.com/api/v1/auth/login/callback
    - https://api.togethercrew.com/api/v1/guilds/connect/callback

**Comment by daniel-ospina** [comment]
same as the other. The suggested setup was already in place
