### ISSUE TITLE
New Choreography: DISCORD_FETCH_MEMBERS

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-discordBot#67]
# Context

Today, the discord-bot only listens to the `Event.DISCORD_BOT.FETCH ` event.

The `Event.DISCORD_BOT.FETCH ` event is called in a choreography called `DISCORD_UPDATE_CHANNELS`. As part of the choreography, we also call the discord-analyzer. When we create / add a guild, we need to fetch the members, but we should not run the analyzer. Therefore we need to create a new choreography that will only call the discord-bot.

# Solution

We have a new choreography: `DISCORD_FETCH_MEMBERS`.

The serverComm will create a saga for this choreography and publish the first event: `Event.DISCORD_BOT.FETCH_MEMBERS`.

## New
- [ ] The discord-bot should consume the event `Event.DISCORD_BOT.FETCH_MEMBERS`
- [ ] The discord-bot should fetch the members for the given guild

## Refactor
- [ ] The event `Event.DISCORD_BOT.FETCH` can be simplified on only run guild extraction.

## Documentation
- https://github.com/RnDAO/tc-messageBroker/issues/35
- https://github.com/RnDAO/tc-serverComm/issues/114

**Comment by scientiststwin** [comment]
FETCH_MEMBERS should be part of `DiscordBotEvent` or `BotEvent`? which one? 

```js
enum BotEvent {
  FETCH = 'FETCH',
  FETCH_MEMBERS = 'FETCH_MEMBERS',
}
```

```js
const DiscordBotEvent = {
  ...BotEvent,
  SEND_MESSAGE: 'SEND_MESSAGE',
  FETCH_MEMBERS = 'FETCH_MEMBERS',
};
```

which one?

**Comment by scientiststwin** [comment]
this task was completed and merged 29th of june
